//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteLab.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Persist Security Info=True;Data Source=DKNRDLAB1;Initial Catalog=remotelabdb;User" +
            " Id=remotelabuser;Password=53cur3LAB!")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password")]
        public string LoginFormPasswordLabel {
            get {
                return ((string)(this["LoginFormPasswordLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.youtube.com/embed/fyM2OHUS6O4?autoplay=1")]
        public string RemoteLabIntroVideoLink {
            get {
                return ((string)(this["RemoteLabIntroVideoLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://answers.syr.edu/display/ischool/iSchool+Remote+Lab")]
        public string OfficialDocumentationLink {
            get {
                return ((string)(this["OfficialDocumentationLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://support.microsoft.com/kb/2592687")]
        public string WindowsClientDownload {
            get {
                return ((string)(this["WindowsClientDownload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://itunes.apple.com/us/app/microsoft-remote-desktop/id715768417?mt=12")]
        public string MacClientDownload {
            get {
                return ((string)(this["MacClientDownload"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          on error resume next\r\n          dim connstr, remotepowershelluser, po" +
            "olName\r\n          connstr = \"{0}\"\r\n          remotepowershelluser = \"{1}\"\r\n     " +
            "     poolName = \"{2}\"\r\n        ")]
        public string RemoteLabSettingsFileContent {
            get {
                return ((string)(this["RemoteLabSettingsFileContent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DashboardMaxEvents {
            get {
                return ((int)(this["DashboardMaxEvents"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RemoteLab Admins")]
        public string AdministratorADGroup {
            get {
                return ((string)(this["AdministratorADGroup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fas.lcl")]
        public string ActiveDirectoryDNSDomain {
            get {
                return ((string)(this["ActiveDirectoryDNSDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("exmail.dickinson.edu")]
        public string SmtpServer {
            get {
                return ((string)(this["SmtpServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("remotelab@dickinson.edu")]
        public string SmtpMessageFromAddress {
            get {
                return ((string)(this["SmtpMessageFromAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fas")]
        public string ActiveDirectoryDomain {
            get {
                return ((string)(this["ActiveDirectoryDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User Name")]
        public string LoginFormUsernameLabel {
            get {
                return ((string)(this["LoginFormUsernameLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11, 81, 123, 99, 77, 112, 206, 101, 241, 209, 26, 218, 152, 28, 143, 229, 146, 26" +
            ", 203, 217, 219, 168, 60, 240, 46, 21, 75, 242, 102, 61, 147, 193")]
        public string EncryptionKeyForPasswords {
            get {
                return ((string)(this["EncryptionKeyForPasswords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          screen mode id:i:2\r\n          desktopwidth:i:{0}\r\n          desktophe" +
            "ight:i:{1}\r\n          session bpp:i:32\r\n          winposstr:s:0,1,614,156,1654,9" +
            "63\r\n          full address:s:{2}\r\n          username:s:{3}\r\n          compressio" +
            "n:i:1\r\n          keyboardhook:i:2\r\n          audiomode:i:0\r\n          redirectpr" +
            "inters:i:1\r\n          redirectcomports:i:0\r\n          redirectsmartcards:i:0\r\n  " +
            "        redirectclipboard:i:1\r\n          redirectposdevices:i:0\r\n          redir" +
            "ectdrives:i:1\r\n          drivestoredirect:s()\r\n          displayconnectionbar:i:" +
            "1\r\n          pinconnectionbar:i:1\r\n          autoreconnection enabled:i:1\r\n     " +
            "     authentication level:i:0\r\n          prompt for credentials:i:0\r\n          n" +
            "egotiate security layer:i:1\r\n          remoteapplicationmode:i:0\r\n          alte" +
            "rnate shell:s:\r\n          shell working directory:s:\r\n          disable wallpape" +
            "r:i:1\r\n          disable full window drag:i:0\r\n          allow desktop compositi" +
            "on:i:1\r\n          allow font smoothing:i:1\r\n          disable menu anims:i:1\r\n  " +
            "        disable themes:i:0\r\n          disable cursor setting:i:0\r\n          bitm" +
            "apcachepersistenable:i:1\r\n          gatewayhostname:s:remote.dickinson.edu\r\n    " +
            "      gatewayusagemethod:i:2\r\n          gatewaycredentialssource:i:4\r\n          " +
            "gatewayprofileusagemethod:i:1\r\n          promptcredentialonce:i:1\r\n          use" +
            " multimon:i:0\r\n          audiocapturemode:i:0\r\n          videoplaybackmode:i:1\r\n" +
            "          connection type:i:6\r\n          redirectdirectx:i:1\r\n          use redi" +
            "rection server name:i:0\r\n          devicestoredirect:s:*\r\n          smart sizing" +
            ":i:1\r\n\r\n        ")]
        public string RdpFileSettings {
            get {
                return ((string)(this["RdpFileSettings"]));
            }
        }
    }
}
